const courses=[
 {id:'ux',title:'UX Design Fundamentals',category:'DESIGN',teacher:'Maya Adebayo',lessons:12,duration:'4h 30m',progress:65,illustration:'✦',class:'design',description:'Learn how to create thoughtful, human-centred digital experiences.',modules:['Introduction to UX thinking','Understanding your users','Research and empathy maps','Wireframes and prototypes','Course assessment']},
 {id:'web',title:'Modern Web Development',category:'TECHNOLOGY',teacher:'David Okoro',lessons:18,duration:'6h 15m',progress:35,illustration:'⌘',class:'',description:'Build responsive, accessible websites with modern tools and practical workflows.',modules:['How the web works','Semantic HTML foundations','CSS layouts and responsive design','JavaScript interactions','Course assessment']},
 {id:'data',title:'Data Analysis with Python',category:'TECHNOLOGY',teacher:'Nneka Obi',lessons:16,duration:'5h 40m',progress:0,illustration:'◫',class:'data',description:'Turn raw data into clear insights using Python and visual storytelling.',modules:['Data analysis foundations','Your first Python notebook','Cleaning datasets','Visualising insight','Course assessment']},
 {id:'business',title:'Build Your First Business',category:'BUSINESS',teacher:'Tunde Bello',lessons:14,duration:'4h 50m',progress:0,illustration:'↗',class:'business',description:'Find your idea, validate it with real people and create a practical launch plan.',modules:['Finding opportunities','Know your customer','Your value proposition','Building your launch plan','Course assessment']},
 {id:'marketing',title:'Digital Marketing Essentials',category:'BUSINESS',teacher:'Zainab Musa',lessons:10,duration:'3h 20m',progress:0,illustration:'◎',class:'',description:'Grow an audience and turn attention into meaningful customer relationships.',modules:['Marketing today','Audience strategy','Content that connects','Measuring campaigns','Course assessment']},
 {id:'product',title:'Product Management Basics',category:'TECHNOLOGY',teacher:'Femi James',lessons:13,duration:'4h 10m',progress:0,illustration:'▣',class:'design',description:'Learn the core habits behind products people genuinely love to use.',modules:['The product mindset','Discovering problems','Prioritising the roadmap','Launching and learning','Course assessment']}
];
let state=JSON.parse(localStorage.getItem('gembuGoState')||'{"enrolled":["ux","web"],"completed":[],"activeCourse":"ux","activeLesson":0}');
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
let catalogueFilter='ALL', catalogueQuery='';
function save(){localStorage.setItem('gembuGoState',JSON.stringify(state))} function course(id){return courses.find(c=>c.id===id)}
function card(c,showProgress=false){const enrolled=state.enrolled.includes(c.id);return `<article class="course-card" data-course="${c.id}"><div class="course-image ${c.class}"><span>${c.category}</span><b class="illustration">${c.illustration}</b></div><div class="course-content"><h3>${c.title}</h3><p>${c.teacher}</p>${showProgress||enrolled?`<div class="progress-wrap"><div class="progress-label"><span>${c.progress? 'In progress':'Not started'}</span><span>${c.progress}%</span></div><div class="progress-bar"><i style="width:${c.progress}%"></i></div></div>`:''}<div class="course-meta"><span>▣ ${c.lessons} lessons</span><span>◷ ${c.duration}</span></div></div></article>`}
function renderCatalogue(){const query=catalogueQuery.toLowerCase();const matches=courses.filter(c=>(catalogueFilter==='ALL'||c.category===catalogueFilter)&&`${c.title} ${c.teacher} ${c.category}`.toLowerCase().includes(query));$('#catalogue-grid').innerHTML=matches.length?matches.map(c=>card(c)).join(''):'<p class="no-results">No courses match that search. Try another topic.</p>';bindCards()}
function render(){const enrolled=courses.filter(c=>state.enrolled.includes(c.id));$('#continue-grid').innerHTML=enrolled.map(c=>card(c,true)).join('');$('#popular-grid').innerHTML=courses.filter(c=>!state.enrolled.includes(c.id)).slice(0,3).map(c=>card(c)).join('');renderCatalogue();$('#learning-grid').innerHTML=enrolled.map(c=>card(c,true)).join('');$('#course-count').textContent=enrolled.length;$('#lesson-count').textContent=enrolled.reduce((a,c)=>a+Math.round(c.lessons*c.progress/100),0);renderCertificates();bindCards()}
function bindCards(){$$('.course-card').forEach(el=>el.onclick=()=>showCourse(el.dataset.course))}
function show(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+view).classList.add('active');$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.view===view));window.scrollTo(0,0)}
function showCourse(id){state.activeCourse=id;save();const c=course(id),enrolled=state.enrolled.includes(id);$('#course-detail').innerHTML=`<div class="detail-hero"><span class="tag">${c.category} · ${c.lessons} LESSONS</span><h1>${c.title}</h1><p>${c.description}</p><p>Created by <b>${c.teacher}</b> · ${c.duration} of learning</p><button class="light-button" id="course-action">${enrolled?'Continue course':'Enroll for free'} <span>→</span></button></div><div class="lesson-layout"><div class="lesson-content"><h2>What you’ll learn</h2><p>Practical, confidence-building lessons that help you apply new skills immediately. Complete each module and pass the final assessment to earn your GembuGo certificate.</p></div><aside class="module-list"><h3>Course content</h3>${c.modules.map((m,i)=>`<div class="module-item ${i===0&&enrolled?'current':''}"><span>${i===c.modules.length-1?'◇':'▶'}</span>${i+1}. ${m}</div>`).join('')}</aside></div>`;show('course-detail');$('#course-action').onclick=()=>{if(!enrolled){state.enrolled.push(id);save();toast('You’re enrolled! Your course is ready.');render()}showLesson(id,0)}}
function showLesson(id,index){const c=course(id);state.activeCourse=id;state.activeLesson=index;save();if(index>=c.modules.length-1)return showQuiz(id);$('#lesson').innerHTML=`<div class="lesson-layout"><article class="lesson-content"><div class="video-placeholder">▶</div><p class="eyebrow">${c.title.toUpperCase()} · LESSON ${index+1}</p><h1>${c.modules[index]}</h1><p>Welcome to this lesson. Here, you’ll build a clear foundation through short explanations and practical examples. Take your time, make notes, and use the ideas in your own work.</p><p>The most useful learning happens when you practise. Once you’re ready, continue to the next lesson to keep your progress moving.</p><button class="primary-button" id="next-lesson">${index===c.modules.length-2?'Take final assessment':'Mark complete & continue'} →</button></article><aside class="module-list"><h3>${c.title}</h3>${c.modules.map((m,i)=>`<div class="module-item ${i<index?'done':''} ${i===index?'current':''}"><span>${i<index?'✓':i===c.modules.length-1?'◇':'▶'}</span>${i+1}. ${m}</div>`).join('')}</aside></div>`;show('lesson');$('#next-lesson').onclick=()=>{c.progress=Math.max(c.progress,Math.round((index+1)/(c.modules.length-1)*85));save();render();showLesson(id,index+1)}}
function showQuiz(id){const c=course(id);$('#quiz').innerHTML=`<div class="quiz-card"><p class="eyebrow">FINAL ASSESSMENT · ${c.title.toUpperCase()}</p><h1>Ready to show what you know?</h1><p>This short quiz checks your understanding of the key ideas in this course.</p><h3>Which approach leads to the strongest learning outcome?</h3><div class="answers"><button class="answer">Memorising answers without practice</button><button class="answer" data-correct="true">Applying ideas through consistent practice</button><button class="answer">Skipping challenging lessons</button><button class="answer">Only studying at the last minute</button></div><button class="primary-button" id="submit-quiz">Submit answer</button></div>`;show('quiz');$$('.answer').forEach(a=>a.onclick=()=>{$$('.answer').forEach(x=>x.classList.remove('selected'));a.classList.add('selected')});$('#submit-quiz').onclick=()=>{if(!$('.answer.selected'))return toast('Choose an answer to continue.');if(!$('.answer.selected').dataset.correct)return toast('Almost — try again. Think about active learning.');completeCourse(id)}}
function completeCourse(id){const c=course(id);c.progress=100;if(!state.completed.includes(id))state.completed.push(id);save();renderCertificates();render();$('#quiz').innerHTML=`<div class="quiz-card quiz-result"><div style="font-size:50px">✦</div><p class="eyebrow">ASSESSMENT COMPLETE</p><h2>Outstanding work!</h2><p>You scored 100% and completed <b>${c.title}</b>. Your certificate is ready.</p><button class="primary-button" id="view-cert">View my certificate</button></div>`;$('#view-cert').onclick=()=>{show('certificates');renderCertificates()};toast('Course complete — certificate unlocked!')}
function renderCertificates(){const list=$('#certificate-list'),empty=$('#certificate-empty');if(!state.completed.length){list.innerHTML='';empty.style.display='block';return}empty.style.display='none';list.innerHTML=state.completed.map(id=>{const c=course(id);return `<div class="certificate"><p class="eyebrow">GEMBUGO CERTIFICATE OF COMPLETION</p><h3>${c.title}</h3><p>This proudly certifies that</p><h2>Amara Mensah</h2><p>has successfully completed this learning programme.</p><p>Issued July 20, 2026 · GembuGo Learning</p></div>`}).join('')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function speak(text){if(!('speechSynthesis'in window))return toast('Text-to-speech is not available in this browser.');window.speechSynthesis.cancel();const chunks=text.match(/.{1,220}(?:\s|$)/g)||[text];chunks.forEach(chunk=>{const utterance=new SpeechSynthesisUtterance(chunk);utterance.rate=.94;window.speechSynthesis.speak(utterance)})}
$('#document-input').addEventListener('change',async e=>{const file=e.target.files[0],status=$('#document-status');if(!file)return;if(file.size>5*1024*1024){status.textContent='Please choose a document smaller than 5 MB.';return}status.textContent=`Reading ${file.name} locally…`;$('#document-output').hidden=true;try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});const response=await fetch('/api/document',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,content:data})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to read this document.');$('#document-summary').textContent=result.summary;$('#document-text').textContent=result.text+(result.truncated?'\n\n[Only the first 30,000 characters are shown.]':'');$('#document-output').hidden=false;status.textContent=`${result.name} is ready. It was processed locally and is not saved.`;$('#read-summary').onclick=()=>speak(result.summary);$('#read-document').onclick=()=>speak(result.text);$('#stop-reading').onclick=()=>window.speechSynthesis?.cancel()}catch(error){status.textContent=error.message||'Unable to read this document.'}});
async function initTutor(){try{const r=await fetch('/api/status'),s=await r.json(),dot=$('.status-dot');if(s.available){dot.classList.add('ready');$('#model-status').textContent='Local model ready';$('#model-detail').textContent=`${s.engine} · ${s.model}`}else{$('#model-status').textContent='Local model not configured';$('#model-detail').textContent='Start server.py with MODEL_PATH to enable private inference.'}}catch(e){$('#model-status').textContent='Open with the local server';$('#model-detail').textContent='Run python3 server.py to connect the offline tutor.'}}
function appendMessage(kind,text){const d=document.createElement('div');d.className='message '+kind;d.innerHTML=`<b>${kind==='user'?'You':'GembuGo Tutor'}</b><p></p>`;d.querySelector('p').textContent=text;$('#chat-history').append(d);$('#chat-history').scrollTop=99999}
$('#chat-form').onsubmit=async e=>{e.preventDefault();const input=$('#chat-input'),message=input.value.trim();if(!message)return;appendMessage('user',message);input.value='';appendMessage('assistant','Thinking locally…');const pending=$$('#chat-history .assistant p')[$$('#chat-history .assistant p').length-1];try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})}),data=await r.json();pending.textContent=data.answer||data.error||'Unable to respond.'}catch(err){pending.textContent='The offline tutor is not connected. Start the local server with a GGUF model to continue.'}};
$$('.prompt-button').forEach(b=>b.onclick=()=>{$('#chat-input').value=b.textContent;$('#chat-form').requestSubmit()});initTutor();
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$$('.chip').forEach(ch=>ch.onclick=()=>{$('.chip.selected').classList.remove('selected');ch.classList.add('selected');catalogueFilter=ch.textContent.trim().split(' ')[0].toUpperCase();renderCatalogue()});$('#course-search').addEventListener('input',e=>{catalogueQuery=e.target.value.trim();catalogueFilter='ALL';$$('.chip').forEach((chip,i)=>chip.classList.toggle('selected',i===0));show('courses');renderCatalogue()});render();
